### ISSUE TITLE
development.rst.txt: typo: lanuage instead of language

### ISSUE THREAD

**Issue by nsajko** [fricas/fricas.github.io#1]
See https://github.com/fricas/fricas.github.io/blob/352f09a6aed7329bdc61609109c81a3095c900b3/development.html#L90

**Comment by oldk1331** [comment]
Fixed in https://github.com/fricas/fricas/commit/4f6aed57249a3703d6b6f1151c74238c243d368b and will be available to https://fricas.github.io in next release.
